

    const movies = [{"Title":"The Hunger Games","Year":"2012","Rated":"PG-13","Released":"23 Mar 2012","Runtime":"142 min","Genre":"Adventure, Sci-Fi, Thriller","Director":"Gary Ross","Writer":"Gary Ross (screenplay), Suzanne Collins (screenplay), Billy Ray (screenplay), Suzanne Collins (novel)","Actors":"Stanley Tucci, Wes Bentley, Jennifer Lawrence, Willow Shields","Plot":"Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.","Language":"English","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 33 wins & 47 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjA4NDg3NzYxMF5BMl5BanBnXkFtZTcwNTgyNzkyNw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.2/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"68/100"}],"Metascore":"68","imdbRating":"7.2","imdbVotes":"775,502","imdbID":"tt1392170","Type":"movie","DVD":"18 Aug 2012","BoxOffice":"$407,981,652","Production":"Lionsgate","Website":"http://thehungergamesmovie.com","Response":"True"},
    {"Title":"Divergent","Year":"2014","Rated":"PG-13","Released":"21 Mar 2014","Runtime":"139 min","Genre":"Adventure, Mystery, Sci-Fi","Director":"Neil Burger","Writer":"Evan Daugherty (screenplay), Vanessa Taylor (screenplay), Veronica Roth (novel)","Actors":"Shailene Woodley, Theo James, Ashley Judd, Jai Courtney","Plot":"In a world divided by factions based on virtues, Tris learns she's Divergent and won't fit in. When she discovers a plot to destroy Divergents, Tris and the mysterious Four must find out what makes Divergents dangerous before it's too late.","Language":"English, Spanish","Country":"USA","Awards":"7 wins & 11 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTYxMzYwODE4OV5BMl5BanBnXkFtZTgwNDE5MzE2MDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.7/10"},{"Source":"Rotten Tomatoes","Value":"41%"},{"Source":"Metacritic","Value":"48/100"}],"Metascore":"48","imdbRating":"6.7","imdbVotes":"388,154","imdbID":"tt1840309","Type":"movie","DVD":"04 Aug 2014","BoxOffice":"$129,520,735","Production":"Lionsgate Films/Summit Entertainment","Website":"http://www.facebook.com/DivergentMovie","Response":"True"},
    {"Title":"Insurgent","Year":"2015","Rated":"PG-13","Released":"20 Mar 2015","Runtime":"119 min","Genre":"Action, Adventure, Sci-Fi","Director":"Robert Schwentke","Writer":"Brian Duffield (screenplay), Akiva Goldsman (screenplay), Mark Bomback (screenplay), Veronica Roth (novel)","Actors":"Kate Winslet, Jai Courtney, Mekhi Phifer, Shailene Woodley","Plot":"Beatrice Prior must confront her inner demons and continue her fight against a powerful alliance which threatens to tear her society apart with the help from others on her side.","Language":"English","Country":"USA","Awards":"3 wins & 17 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTgxOTYxMTg3OF5BMl5BanBnXkFtZTgwMDgyMzA2NDE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"},{"Source":"Rotten Tomatoes","Value":"29%"},{"Source":"Metacritic","Value":"42/100"}],"Metascore":"42","imdbRating":"6.2","imdbVotes":"191,180","imdbID":"tt2908446","Type":"movie","DVD":"04 Aug 2015","BoxOffice":"$114,138,208","Production":"Lionsgate Films","Website":"http://www.thedivergentseries.com/","Response":"True"},
    {"Title":"Jurassic World","Year":"2015","Rated":"PG-13","Released":"12 Jun 2015","Runtime":"124 min","Genre":"Action, Adventure, Sci-Fi","Director":"Colin Trevorrow","Writer":"Rick Jaffa (screenplay by), Amanda Silver (screenplay by), Colin Trevorrow (screenplay by), Derek Connolly (screenplay by), Rick Jaffa (story by), Amanda Silver (story by), Michael Crichton (based on the characters created by)","Actors":"Chris Pratt, Bryce Dallas Howard, Irrfan Khan, Vincent D'Onofrio","Plot":"A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, which escapes containment and goes on a killing spree.","Language":"English","Country":"USA","Awards":"14 wins & 57 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzQ3OTY4NjAtNzM5OS00N2ZhLWJlOWUtYzYwZjNmOWRiMzcyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"71%"},{"Source":"Metacritic","Value":"59/100"}],"Metascore":"59","imdbRating":"7.0","imdbVotes":"515,266","imdbID":"tt0369610","Type":"movie","DVD":"20 Oct 2015","BoxOffice":"$528,757,749","Production":"Universal Pictures","Website":"http://www.jurassicworldmovie.com/","Response":"True"}
];

export default movies;

