export const userActionsTypes = {
    AUTHENTICATION_SUCCESS: 'authenticated_user',
    UNAUTHENTICATED: 'unauthenticated_user',
    AUTHENTICATION_ERROR: 'authentication_error',
    ADD_FRIENDS_SUCCESS: 'ADD_FRIENDS_SUCCESS',
    ADD_FRIENDS_ERROR: 'ADD_FRIENDS_ERROR',
    DELETE_FRIENDS: '.DELETE_FRIENDS'


};


export const friendsViewActionTypes ={
    CURRENT_USER_START_LOADING:'CURRENT_USER_START_LOADING',
    CURRENT_USER_LOADING_SUCCESS: ' CURRENT_USER_LOADING_SUCCESS',
    CURRENT_USER_LOADING_FAILURE: 'CURRENT_USER_LOADING_FAILURE'
};
